import type { ZeroAPISpec, ResourceDefinition, FieldDefinition, FieldType } from '../types/spec.js'
import { renderRelationFields, renderJoinModels } from '../relations/index.js'

const PRISMA_TYPE_MAP: Record<FieldType, string> = {
  string: 'String', text: 'String', email: 'String', url: 'String', uuid: 'String',
  number: 'Float', integer: 'Int', decimal: 'Decimal', boolean: 'Boolean',
  date: 'DateTime', datetime: 'DateTime',
  file: 'String',        // stored as URL
  'file[]': 'String',    // stored as URL list (schema-level rendering handled in Phase 1+)
  json: 'Json',
  enum: 'String',        // enum rendering handled in Phase 1+
}

function renderField(name: string, field: FieldDefinition): string {
  const prismaType = PRISMA_TYPE_MAP[field.type]
  const optional   = field.required ? '' : '?'
  const unique     = field.unique ? ' @unique' : ''

  let defaultClause = ''
  if (field.default !== undefined && field.default !== null) {
    defaultClause =
      typeof field.default === 'string'
        ? ` @default("${field.default}")`
        : ` @default(${String(field.default)})`
  }

  return `  ${name.padEnd(14)}${prismaType}${optional}${unique}${defaultClause}`
}

const RESERVED_FIELDS = new Set(['id', 'createdAt', 'updatedAt'])

function resourceHasOwnOnly(spec: ZeroAPISpec, resourceName: string): boolean {
  return (spec.permissions ?? []).some(
    (p) => p.resource === resourceName && p.rules.some((r) => r.ownOnly),
  )
}

function renderModel(
  resource: ResourceDefinition,
  allResources: ResourceDefinition[],
  ownedByUser: boolean,
): string {
  const modelName = resource.name.charAt(0).toUpperCase() + resource.name.slice(1)

  // FK fields owned by relations — must not be re-declared from spec fields
  const relationFkFields = new Set<string>()
  for (const rel of resource.relations ?? []) {
    if (rel.type === 'manyToOne' || rel.type === 'oneToOne') {
      relationFkFields.add(rel.field ?? `${rel.resource.toLowerCase()}Id`)
    }
  }
  // Skip a spec-declared "userId" field when ownership injection owns the column,
  // so we don't emit it twice.
  if (ownedByUser) relationFkFields.add('userId')

  const baseFields = [
    `  id            String   @id @default(cuid())`,
    `  createdAt     DateTime @default(now())`,
    `  updatedAt     DateTime @updatedAt`,
    ...Object.entries(resource.fields)
      .filter(([name]) => !RESERVED_FIELDS.has(name) && !relationFkFields.has(name))
      .map(([name, field]) => renderField(name, field)),
  ]

  if (ownedByUser) {
    baseFields.push(`  userId        String`)
    baseFields.push(`  user          User     @relation(fields: [userId], references: [id], onDelete: Cascade)`)
  }

  const relationLines = renderRelationFields(resource, allResources)

  return `model ${modelName} {\n${[...baseFields, ...relationLines].join('\n')}\n}`
}

/**
 * Generates a complete Prisma schema string from a ZeroAPI spec.
 * Includes all models, relation fields, and join models for manyToMany relations.
 */
export function generatePrismaSchema(spec: ZeroAPISpec): string {
  const header = `// Generated by @ludagg/zeroapi-runtime — do not edit manually
// Spec: ${spec.name} v${spec.version}

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}`

  // Deep-clone resources so renderJoinModels can mutate the copy safely
  const resources = spec.resources.map((r) => ({ ...r, relations: r.relations ? [...r.relations] : undefined }))

  const ownedResources = resources.filter((r) => resourceHasOwnOnly(spec, r.name))

  const models = resources
    .map((r) => renderModel(r, resources, resourceHasOwnOnly(spec, r.name)))
    .join('\n\n')

  // Collect join models (manyToMany)
  const joinModels: string[] = []
  const seen = new Set<string>()
  for (const resource of resources) {
    for (const rel of resource.relations ?? []) {
      if (rel.type === 'manyToMany' && rel.through && !seen.has(rel.through)) {
        seen.add(rel.through)
        const generated = renderJoinModels(resource, resources)
        joinModels.push(...generated)
      }
    }
  }

  // Phase 1.1: API-key storage model — emitted whenever apikey auth is active
  const apiKeyAuthEnabled =
    spec.auth?.strategy === 'apikey' || spec.auth?.apikey?.enabled === true
  const apiKeyModel = apiKeyAuthEnabled ? renderApiKeyModel() : null

  // Phase 1.2: JWT user system — emit User + RefreshToken when opted in.
  // Phase 1.3: extend User with back-relations for each ownOnly-owned resource.
  const jwtUserSystemEnabled = spec.auth?.jwt?.enabled === true
  const jwtUserModels = jwtUserSystemEnabled
    ? renderJwtUserModels(ownedResources.map((r) => r.name))
    : []

  const parts = [header, models, ...joinModels, apiKeyModel, ...jwtUserModels].filter(Boolean)
  return parts.join('\n\n') + '\n'
}

function renderApiKeyModel(): string {
  return `model ApiKey {
  id         String    @id @default(uuid())
  keyHash    String    @unique
  keyPrefix  String
  name       String?
  role       String    @default("admin")
  revoked    Boolean   @default(false)
  lastUsedAt DateTime?
  createdAt  DateTime  @default(now())
}`
}

function renderJwtUserModels(ownedResourceNames: string[]): string[] {
  const ownedLines = ownedResourceNames.map((name) => {
    const modelName = name.charAt(0).toUpperCase() + name.slice(1)
    // Field name is the lower-cased plural model name to avoid collisions with refreshTokens.
    const field = `owned${modelName}s`
    return `  ${field.padEnd(13)} ${modelName}[]`
  })

  const userModel = `model User {
  id            String    @id @default(uuid())
  email         String    @unique
  passwordHash  String
  salt          String
  role          String    @default("user")
  emailVerified Boolean   @default(false)
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  refreshTokens RefreshToken[]${ownedLines.length > 0 ? '\n' + ownedLines.join('\n') : ''}
}`

  const refreshTokenModel = `model RefreshToken {
  id        String   @id @default(uuid())
  tokenHash String   @unique
  userId    String
  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  expiresAt DateTime
  revoked   Boolean  @default(false)
  createdAt DateTime @default(now())
}`

  return [userModel, refreshTokenModel]
}
