import type { ZeroAPISpec, ResourceDefinition, FieldDefinition, FieldType } from '../types/spec.js'

const PRISMA_TYPE_MAP: Record<FieldType, string> = {
  string: 'String',
  text: 'String',
  number: 'Float',
  integer: 'Int',
  boolean: 'Boolean',
  date: 'DateTime',
  datetime: 'DateTime',
  email: 'String',
  url: 'String',
  uuid: 'String',
}

function renderField(name: string, field: FieldDefinition): string {
  const prismaType = PRISMA_TYPE_MAP[field.type]
  const optional = field.required ? '' : '?'
  const unique = field.unique ? ' @unique' : ''

  let defaultClause = ''
  if (field.default !== undefined && field.default !== null) {
    defaultClause =
      typeof field.default === 'string'
        ? ` @default("${field.default}")`
        : ` @default(${String(field.default)})`
  }

  return `  ${name.padEnd(14)}${prismaType}${optional}${unique}${defaultClause}`
}

function renderModel(resource: ResourceDefinition): string {
  const modelName = resource.name.charAt(0).toUpperCase() + resource.name.slice(1)
  const fields = [
    `  id            String   @id @default(cuid())`,
    `  createdAt     DateTime @default(now())`,
    `  updatedAt     DateTime @updatedAt`,
    ...Object.entries(resource.fields).map(([name, field]) => renderField(name, field)),
  ]
  return `model ${modelName} {\n${fields.join('\n')}\n}`
}

/**
 * Generates a complete Prisma schema string from a ZeroAPI spec.
 * Each resource becomes a model with auto-managed id, createdAt, updatedAt fields.
 */
export function generatePrismaSchema(spec: ZeroAPISpec): string {
  const header = `// Generated by @zeroapi/runtime — do not edit manually
// Spec: ${spec.name} v${spec.version}

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}`

  const models = spec.resources.map(renderModel).join('\n\n')
  return `${header}\n\n${models}\n`
}
