import type { ZeroAPISpec, ResourceDefinition, FieldDefinition, FieldType } from '../types/spec.js'
import { renderRelationFields, renderJoinModels } from '../relations/index.js'

const PRISMA_TYPE_MAP: Record<FieldType, string> = {
  string: 'String', text: 'String', email: 'String', url: 'String', uuid: 'String',
  number: 'Float', integer: 'Int', boolean: 'Boolean',
  date: 'DateTime', datetime: 'DateTime',
  file: 'String',  // stored as URL
}

function renderField(name: string, field: FieldDefinition): string {
  const prismaType = PRISMA_TYPE_MAP[field.type]
  const optional   = field.required ? '' : '?'
  const unique     = field.unique ? ' @unique' : ''

  let defaultClause = ''
  if (field.default !== undefined && field.default !== null) {
    defaultClause =
      typeof field.default === 'string'
        ? ` @default("${field.default}")`
        : ` @default(${String(field.default)})`
  }

  return `  ${name.padEnd(14)}${prismaType}${optional}${unique}${defaultClause}`
}

const RESERVED_FIELDS = new Set(['id', 'createdAt', 'updatedAt'])

function renderModel(resource: ResourceDefinition, allResources: ResourceDefinition[]): string {
  const modelName = resource.name.charAt(0).toUpperCase() + resource.name.slice(1)

  // FK fields owned by relations — must not be re-declared from spec fields
  const relationFkFields = new Set<string>()
  for (const rel of resource.relations ?? []) {
    if (rel.type === 'manyToOne' || rel.type === 'oneToOne') {
      relationFkFields.add(rel.field ?? `${rel.resource.toLowerCase()}Id`)
    }
  }

  const baseFields = [
    `  id            String   @id @default(cuid())`,
    `  createdAt     DateTime @default(now())`,
    `  updatedAt     DateTime @updatedAt`,
    ...Object.entries(resource.fields)
      .filter(([name]) => !RESERVED_FIELDS.has(name) && !relationFkFields.has(name))
      .map(([name, field]) => renderField(name, field)),
  ]

  const relationLines = renderRelationFields(resource, allResources)

  return `model ${modelName} {\n${[...baseFields, ...relationLines].join('\n')}\n}`
}

/**
 * Generates a complete Prisma schema string from a ZeroAPI spec.
 * Includes all models, relation fields, and join models for manyToMany relations.
 */
export function generatePrismaSchema(spec: ZeroAPISpec): string {
  const header = `// Generated by @ludagg/zeroapi-runtime — do not edit manually
// Spec: ${spec.name} v${spec.version}

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}`

  // Deep-clone resources so renderJoinModels can mutate the copy safely
  const resources = spec.resources.map((r) => ({ ...r, relations: r.relations ? [...r.relations] : undefined }))

  const models = resources.map((r) => renderModel(r, resources)).join('\n\n')

  // Collect join models (manyToMany)
  const joinModels: string[] = []
  const seen = new Set<string>()
  for (const resource of resources) {
    for (const rel of resource.relations ?? []) {
      if (rel.type === 'manyToMany' && rel.through && !seen.has(rel.through)) {
        seen.add(rel.through)
        const generated = renderJoinModels(resource, resources)
        joinModels.push(...generated)
      }
    }
  }

  const parts = [header, models, ...joinModels].filter(Boolean)
  return parts.join('\n\n') + '\n'
}
