import type { ZeroAPISpec, ResourceDefinition, FieldDefinition, CrudAction } from '../types/spec.js'

const DEFAULT_ENDPOINTS: CrudAction[] = ['list', 'create', 'read', 'update', 'delete']

function fieldFixtureValue(name: string, field: FieldDefinition): string {
  switch (field.type) {
    case 'email':
      return `'test-${name}@example.com'`
    case 'url':
      return `'https://example.com/${name}'`
    case 'uuid':
      return `crypto.randomUUID()`
    case 'number':
      return String(field.min ?? 1)
    case 'integer':
      return String(Math.ceil(field.min ?? 1))
    case 'boolean':
      return 'true'
    case 'date':
    case 'datetime':
      return `new Date().toISOString()`
    default:
      return `'test-${name}'`
  }
}

function buildCreateFixture(resource: ResourceDefinition): string {
  const entries = Object.entries(resource.fields)
    .filter(([, field]) => field.required)
    .map(([name, field]) => `    ${name}: ${fieldFixtureValue(name, field)}`)
  return entries.length > 0 ? `{\n${entries.join(',\n')}\n  }` : '{}'
}

function generateResourceTests(resource: ResourceDefinition): string {
  const name = resource.name
  const path = `/${name.toLowerCase()}s`
  const endpoints: CrudAction[] = resource.endpoints ?? DEFAULT_ENDPOINTS
  const fixture = buildCreateFixture(resource)
  const lines: string[] = []

  lines.push(`describe('${name} routes', () => {`)
  lines.push(`  let createdId: string`)
  lines.push(``)

  if (endpoints.includes('list')) {
    lines.push(`  it('GET ${path} — lists ${name.toLowerCase()}s', async () => {`)
    lines.push(`    const res = await app.request('${path}')`)
    lines.push(`    expect(res.status).toBe(200)`)
    lines.push(`    const body = await res.json() as { data: unknown[]; count: number }`)
    lines.push(`    expect(Array.isArray(body.data)).toBe(true)`)
    lines.push(`    expect(typeof body.count).toBe('number')`)
    lines.push(`  })`)
    lines.push(``)
  }

  if (endpoints.includes('create')) {
    lines.push(`  it('POST ${path} — creates a ${name.toLowerCase()}', async () => {`)
    lines.push(`    const res = await app.request('${path}', {`)
    lines.push(`      method: 'POST',`)
    lines.push(`      headers: { 'Content-Type': 'application/json' },`)
    lines.push(`      body: JSON.stringify(${fixture}),`)
    lines.push(`    })`)
    lines.push(`    expect(res.status).toBe(201)`)
    lines.push(`    const body = await res.json() as { data: { id: string } }`)
    lines.push(`    expect(typeof body.data.id).toBe('string')`)
    lines.push(`    createdId = body.data.id`)
    lines.push(`  })`)
    lines.push(``)
  }

  if (endpoints.includes('read')) {
    lines.push(`  it('GET ${path}/:id — reads a ${name.toLowerCase()} by id', async () => {`)
    lines.push(`    const res = await app.request(\`${path}/\${createdId}\`)`)
    lines.push(`    expect(res.status).toBe(200)`)
    lines.push(`    const body = await res.json() as { data: { id: string } }`)
    lines.push(`    expect(body.data.id).toBe(createdId)`)
    lines.push(`  })`)
    lines.push(``)
  }

  if (endpoints.includes('update')) {
    lines.push(`  it('PUT ${path}/:id — updates a ${name.toLowerCase()}', async () => {`)
    lines.push(`    const res = await app.request(\`${path}/\${createdId}\`, {`)
    lines.push(`      method: 'PUT',`)
    lines.push(`      headers: { 'Content-Type': 'application/json' },`)
    lines.push(`      body: JSON.stringify({}),`)
    lines.push(`    })`)
    lines.push(`    expect(res.status).toBe(200)`)
    lines.push(`    const body = await res.json() as { data: { id: string } }`)
    lines.push(`    expect(body.data.id).toBe(createdId)`)
    lines.push(`  })`)
    lines.push(``)
  }

  if (endpoints.includes('delete')) {
    lines.push(`  it('DELETE ${path}/:id — deletes a ${name.toLowerCase()}', async () => {`)
    lines.push(`    const res = await app.request(\`${path}/\${createdId}\`, {`)
    lines.push(`      method: 'DELETE',`)
    lines.push(`    })`)
    lines.push(`    expect(res.status).toBe(200)`)
    lines.push(`  })`)
    lines.push(``)
  }

  lines.push(`  it('GET ${path}/unknown-id — returns 404', async () => {`)
  lines.push(`    const res = await app.request('${path}/non-existent-id')`)
  lines.push(`    expect(res.status).toBe(404)`)
  lines.push(`  })`)
  lines.push(`})`)

  return lines.join('\n')
}

/**
 * Generates a ready-to-run Vitest test suite as a string for the given spec.
 * The generated tests cover all enabled CRUD endpoints for each resource.
 */
export function generateTests(spec: ZeroAPISpec): string {
  const resourceTests = spec.resources.map(generateResourceTests).join('\n\n')

  return `// Generated by @ludagg/zeroapi-runtime — do not edit manually
// Spec: ${spec.name} v${spec.version}

import { describe, it, expect } from 'vitest'
import { createRuntime } from '@ludagg/zeroapi-runtime'

const spec = ${JSON.stringify(spec, null, 2)} as const

const { app } = createRuntime(spec, { enableLogging: false })

${resourceTests}
`
}
