import { writeFile, mkdir, unlink, readFile, stat } from 'fs/promises'
import { existsSync } from 'fs'
import { join, extname, basename } from 'path'
import { randomUUID } from 'crypto'
import type { Hono, Context } from 'hono'
import type { StorageProvider, UploadInput, UploadOutput } from './provider.js'

export const OAUTH_CALLBACK_BASE_ENV = 'OAUTH_CALLBACK_BASE_URL'

export interface LocalStorageOptions {
  /** Directory where files are written. Defaults to `./uploads`. */
  uploadDir?: string
  /**
   * Base URL prefix used to build public URLs. Defaults to
   * `OAUTH_CALLBACK_BASE_URL` env var, then `http://localhost:3000`.
   */
  baseUrl?: string
}

function stripTrailingSlash(s: string): string {
  return s.endsWith('/') ? s.slice(0, -1) : s
}

function safeKey(key: string): string {
  // Block traversal, absolute paths, NUL bytes. Keys are generated by upload(),
  // so this only matters when the caller passes a key from URL/body input.
  if (
    !key ||
    key.includes('/') || key.includes('\\') || key.includes('\0') ||
    key === '.' || key === '..' || key.startsWith('..')
  ) {
    throw new Error(`Invalid storage key: ${key}`)
  }
  const flat = basename(key)
  if (flat !== key) throw new Error(`Invalid storage key: ${key}`)
  return flat
}

const MIME_EXT: Record<string, string> = {
  'image/jpeg': '.jpg', 'image/png': '.png', 'image/webp': '.webp',
  'image/gif': '.gif', 'image/svg+xml': '.svg',
  'application/pdf': '.pdf',
  'text/plain': '.txt', 'text/csv': '.csv',
  'application/json': '.json',
}

function chooseExt(filename: string, mimeType: string): string {
  return extname(filename) || MIME_EXT[mimeType] || ''
}

/**
 * Filesystem-backed `StorageProvider`. Suitable for development, tests, or
 * deployments with a persistent disk. NOT safe on ephemeral containers — the
 * runtime emits a loud warning when this is selected in production (see
 * `resolveStorageProvider` in `./factory.ts`).
 */
export class LocalStorage implements StorageProvider {
  readonly uploadDir: string
  private readonly baseUrl: string

  constructor(options: LocalStorageOptions = {}) {
    this.uploadDir = options.uploadDir ?? './uploads'
    this.baseUrl = stripTrailingSlash(
      options.baseUrl ??
      process.env[OAUTH_CALLBACK_BASE_ENV] ??
      'http://localhost:3000'
    )
  }

  async upload(file: UploadInput): Promise<UploadOutput> {
    await mkdir(this.uploadDir, { recursive: true })
    const ext = chooseExt(file.filename, file.mimeType)
    const key = `${randomUUID()}${ext}`
    await writeFile(join(this.uploadDir, key), file.buffer)
    return { key, url: this.getUrl(key) }
  }

  async delete(key: string): Promise<void> {
    const flat = safeKey(key)
    const full = join(this.uploadDir, flat)
    try {
      await unlink(full)
    } catch (err) {
      // ENOENT is fine — the file is already gone. Anything else bubbles up.
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err
    }
  }

  getUrl(key: string): string {
    const flat = safeKey(key)
    return `${this.baseUrl}/uploads/${flat}`
  }

  /** Resolve a key to its full filesystem path. */
  pathFor(key: string): string {
    return join(this.uploadDir, safeKey(key))
  }
}

/**
 * Mounts the `GET /uploads/:key` route that serves files written by
 * `LocalStorage`. Called by the runtime when the resolved provider is local.
 */
export function mountLocalUploadRoute(app: Hono, storage: LocalStorage): void {
  app.get('/uploads/:key', async (c: Context) => {
    const raw = c.req.param('key')
    if (!raw) return c.json({ error: 'Missing key' }, 400)
    let key: string
    try { key = safeKey(raw) }
    catch { return c.json({ error: 'Invalid key' }, 400) }

    const path = join(storage.uploadDir, key)
    if (!existsSync(path)) return c.json({ error: 'Not found' }, 404)

    try {
      const [data, info] = await Promise.all([readFile(path), stat(path)])
      const ext = extname(key).toLowerCase()
      const ct = EXT_MIME[ext] ?? 'application/octet-stream'
      return new Response(new Uint8Array(data), {
        status: 200,
        headers: {
          'content-type': ct,
          'content-length': String(info.size),
          'cache-control': 'public, max-age=3600',
        },
      })
    } catch {
      return c.json({ error: 'Failed to read file' }, 500)
    }
  })
}

const EXT_MIME: Record<string, string> = {
  '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png',
  '.webp': 'image/webp', '.gif': 'image/gif', '.svg': 'image/svg+xml',
  '.pdf': 'application/pdf',
  '.txt': 'text/plain; charset=utf-8', '.csv': 'text/csv',
  '.json': 'application/json',
}
